import { EventKinds } from '@/modules/events/domain/event.enums';

export const DISASTER_KIND_BY_NAME: Record<string, EventKinds> = {
  AI: EventKinds.Ai,
  가뭄: EventKinds.Drought,
  가축질병: EventKinds.Livestock,
  강풍: EventKinds.Wind,
  건조: EventKinds.Dry,
  교통: EventKinds.Transport,
  교통사고: EventKinds.TrafficCrash,
  교통통제: EventKinds.TrafficCtrl,
  금융: EventKinds.Finance,
  기타: EventKinds.Other,
  대설: EventKinds.Snow,
  미세먼지: EventKinds.FineDust,
  민방공: EventKinds.CivDef,
  붕괴: EventKinds.Collapse,
  산불: EventKinds.Wildfire,
  산사태: EventKinds.Landslide,
  수도: EventKinds.Water,
  안개: EventKinds.Fog,
  인파밀집: EventKinds.CrowdDensity,
  사이버: EventKinds.Cyber,
  에너지: EventKinds.Energy,
  전염병: EventKinds.Epidemic,
  정전: EventKinds.Blackout,
  지진: EventKinds.Quake,
  지진해일: EventKinds.Tsunami,
  태풍: EventKinds.Typhoon,
  테러: EventKinds.Terror,
  통신: EventKinds.Telecom,
  폭발: EventKinds.Explosion,
  폭염: EventKinds.Heat,
  풍랑: EventKinds.HighSeas,
  한파: EventKinds.Cold,
  호우: EventKinds.Rain,
  홍수: EventKinds.Flood,
  화재: EventKinds.Fire,
  환경오염사고: EventKinds.Pollution,
  오존: EventKinds.O3,
  우주환경: EventKinds.SpaceWeather,
  항공사고: EventKinds.AviationAccident,
  해양사고: EventKinds.MarineAccident,
  야생동물출현: EventKinds.WildAnimal,
  황사: EventKinds.YellowDust,
};

export const DISASTER_KIND_LABELS = Object.keys(DISASTER_KIND_BY_NAME) as [string, ...string[]];
